# DB
spring:
  profiles:
    include: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/approval?characterEncoding=UTF-8&serverTimezone=UTC
    username: approval
    password: 1234

  # Spring Multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true

# AWS
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: approval-s3

# Logging level
logging:
  level:
    com:
      umc:
        approval: debug

#Ncloud SMS API
ncloud:
  sms:
    accessKey: none
    secretKey: none
    serviceId: none
    senderPhone: none