# DB
spring:
  profiles:
    include: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/approval?characterEncoding=UTF-8&serverTimezone=UTC
    username: approval
    password: 1234

# JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true

# Logging level
logging:
  level:
    com:
      umc:
        approval: debug