# DB
spring:
  profiles:
    include: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/approval?characterEncoding=UTF-8&serverTimezone=UTC
    username: approval
    password: 1234
  config:
    use-legacy-processing: true

  # Spring Multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

# Ncloud SMS API
accessKey: 123
secretKey: 123
serviceId: 123
senderPhone: 123

# Logging level
logging:
  level:
    com:
      umc:
        approval: debug